if pthreads.h is not found, configure errors out now added test for unsetenv, implement environment::remove() using setValue() for 	systems without it

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9559,6 +9559,7 @@ echo
 echo "***** threads ****************"
 
 
+HAVE_PTHREADS=""
 PTHREADSINCLUDES=""
 
 if ( test "$cross_compiling" = "yes" )
@@ -9568,6 +9569,7 @@ then
 	if ( test -n "$PTHREADSPATH" )
 	then
 		PTHREADSINCLUDES="-I$PTHREADSPATH/include"
+		HAVE_PTHREADS="yes"
 	fi
 
 else
@@ -9577,6 +9579,7 @@ echo $ECHO_N "checking for /usr/include/$i.h... $ECHO_C" >&6
 	then
 		echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+		HAVE_PTHREADS="yes"
 		break
 	else
 		echo "$as_me:$LINENO: result: no" >&5
@@ -9594,6 +9597,7 @@ echo $ECHO_N "checking for $j/pthread.h... $ECHO_C" >&6
 						PTHREADSINCLUDES="-I$j"
 						echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+						HAVE_PTHREADS="yes"
 						break
 					fi
 					echo "$as_me:$LINENO: result: no" >&5
@@ -9604,6 +9608,13 @@ echo "${ECHO_T}no" >&6
 	fi
 fi
 
+if ( test -z "$HAVE_PTHREADS" )
+then
+	{ { echo "$as_me:$LINENO: error: pthreads.h not found.  Rudiments requires this file." >&5
+echo "$as_me: error: pthreads.h not found.  Rudiments requires this file." >&2;}
+   { (exit 1); exit 1; }; }
+	exit
+fi
 
 echo "******************************"
 
@@ -12032,7 +12043,8 @@ fi
 
 
 
-for ac_func in regcomp regcmp re_comp sem_open setenv putenv
+
+for ac_func in regcomp regcmp re_comp sem_open setenv putenv unsetenv
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
