*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23246,6 +23246,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
+/* linux style */
 struct statfs sfs;
 sfs.f_type=0;
 sfs.f_bsize=0;
@@ -23308,6 +23309,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
+/* cygwin style */
 struct statfs sfs;
 sfs.f_type=0;
 sfs.f_bsize=0;
@@ -23372,6 +23374,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
+/* freebsd style */
 struct statfs sfs;
 sfs.f_bsize=0;
 sfs.f_iosize=0;
@@ -23445,6 +23448,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
+/* netbsd style */
 struct statfs sfs;
 sfs.f_type=0;
 sfs.f_bsize=0;
@@ -23494,7 +23498,84 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_NETBSD_STATFS 1
 _ACEOF
- STATFS_STYLE="netbsd style"
+ STATFS_STYLE="old netbsd style"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+if ( test "$STATFS_STYLE" = "unknown" )
+then
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/statvfs.h>
+int
+main ()
+{
+/* netbsd-3.0 style */
+struct statvfs sfs;
+sfs.f_flag=0;
+sfs.f_bsize=0;
+sfs.f_frsize=0;
+sfs.f_iosize=0;
+sfs.f_blocks=0;
+sfs.f_bfree=0;
+sfs.f_bavail=0;
+sfs.f_bresvd=0;
+sfs.f_files=0;
+sfs.f_ffree=0;
+sfs.f_favail=0;
+sfs.f_syncreads=0;
+sfs.f_syncwrites=0;
+sfs.f_asyncreads=0;
+sfs.f_asyncwrites=0;
+sfs.f_fsidx.__fsid_val[0]=0;
+sfs.f_fsid=0;
+sfs.f_namemax=0;
+sfs.f_owner=0;
+sfs.f_fstypename[0]=0;
+sfs.f_mntonname[0]=0;
+sfs.f_mntfromname[0]=0;
+statvfs("/",&sfs);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_NETBSD_STATVFS 1
+_ACEOF
+ STATFS_STYLE="netbsd-3.0 style"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -23516,6 +23597,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
+/* openbsd style */
 struct statfs sfs;
 sfs.f_flags=0;
 sfs.f_bsize=0;
@@ -23587,6 +23669,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
+/* darwin style */
 struct statfs sfs;
 sfs.f_otype=0;
 sfs.f_oflags=0;
@@ -23658,6 +23741,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
+/* statvfs style */
 struct statvfs sfs;
 sfs.f_bsize=0;
 sfs.f_frsize=0;
